# print today date in the name of Excel file
dateOn: False

# time range to scan
period_timeframe:   ['7d', '30d', '90d', '180d']

interval_timeframe: ['1d',  '1d',  '1d',  '1d']

# indexes (columns)
# indexes from https://it.finance.yahoo.com/
comparison_symbols: [
'BTC-USD'
]

# indexes (rows)
# indexes from https://it.finance.yahoo.com/
symbols: [
# S&P 500
'^GSPC',
# Gold
'GC=F',
# VIX
'^VIX',
# Nasdaq
'^NDX'
]

rowNames: [
'S&P 500',
'Gold',
'VIX',
'Nasdaq'
]

columnsNames: [
  'Bitcoin'
]